import { useState } from 'react'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Slider } from '@/components/ui/slider'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { scenarioConfigs, industryImpacts, timelineEvents } from '@/data/mockData'
import { formatNumber } from '@/lib/utils'
import { cn } from '@/lib/utils'
import { AlertTriangle, Clock, DollarSign, TrendingDown, RefreshCw, X, Download, BarChart3 } from 'lucide-react'

export function Scenarios() {
  const [activeScenario, setActiveScenario] = useState('destruction')
  const [stockpileDays, setStockpileDays] = useState([45])
  const [usaReshoring, setUsaReshoring] = useState([50])
  const [nearshoring, setNearshoring] = useState([20])
  const [isRecalculating, setIsRecalculating] = useState(false)
  const [showCompareModal, setShowCompareModal] = useState(false)

  const currentScenario = scenarioConfigs.find(s => s.id === activeScenario) || scenarioConfigs[3]

  const calculateMitigatedLoss = (scenario = currentScenario) => {
    const baseLoss = scenario.economicImpactUSD
    const stockpileReduction = (stockpileDays[0] / 180) * 0.15
    const reshoringReduction = (usaReshoring[0] / 100) * 0.25
    const nearshoringReduction = (nearshoring[0] / 50) * 0.10
    const totalReduction = stockpileReduction + reshoringReduction + nearshoringReduction
    return baseLoss * (1 - Math.min(totalReduction, 0.5))
  }

  const handleRecalculate = () => {
    setIsRecalculating(true)
    // Simulate recalculation with a brief delay for visual feedback
    setTimeout(() => {
      setIsRecalculating(false)
    }, 800)
  }

  const handleExportReport = () => {
    // Generate a comprehensive risk report
    const canvas = document.createElement('canvas')
    const ctx = canvas.getContext('2d')
    
    canvas.width = 1200
    canvas.height = 1600
    
    if (ctx) {
      // Background
      ctx.fillStyle = '#0F1629'
      ctx.fillRect(0, 0, canvas.width, canvas.height)
      
      // Header
      ctx.fillStyle = '#FFFFFF'
      ctx.font = 'bold 32px Inter, system-ui, sans-serif'
      ctx.fillText('Taiwan Disruption Risk Report', 40, 60)
      
      ctx.font = '16px Inter, system-ui, sans-serif'
      ctx.fillStyle = '#94A3B8'
      ctx.fillText('Generated by Vigia - Taiwan Risk Intelligence Platform', 40, 95)
      ctx.fillText(`Report Date: ${new Date().toLocaleString()}`, 40, 120)
      
      // Divider
      ctx.strokeStyle = '#252D4A'
      ctx.lineWidth = 2
      ctx.beginPath()
      ctx.moveTo(40, 145)
      ctx.lineTo(1160, 145)
      ctx.stroke()
      
      // Current Scenario Section
      ctx.font = 'bold 24px Inter, system-ui, sans-serif'
      ctx.fillStyle = '#DC2626'
      ctx.fillText(`Active Scenario: ${currentScenario.name}`, 40, 190)
      
      ctx.font = '16px Inter, system-ui, sans-serif'
      ctx.fillStyle = '#E2E8F0'
      ctx.fillText(`• Production Drop: ${currentScenario.productionDropPercent}%`, 60, 230)
      ctx.fillText(`• Duration: ${currentScenario.durationMonths} months`, 60, 260)
      ctx.fillText(`• Annual Probability: ${(currentScenario.probabilityAnnual * 100).toFixed(0)}%`, 60, 290)
      ctx.fillText(`• Economic Impact: ${formatNumber(currentScenario.economicImpactUSD)}`, 60, 320)
      
      // Mitigation Strategy Section
      ctx.font = 'bold 24px Inter, system-ui, sans-serif'
      ctx.fillStyle = '#3B82F6'
      ctx.fillText('Mitigation Strategy Configuration', 40, 380)
      
      ctx.font = '16px Inter, system-ui, sans-serif'
      ctx.fillStyle = '#E2E8F0'
      ctx.fillText(`• Strategic Stockpile: ${stockpileDays[0]} days`, 60, 420)
      ctx.fillText(`• USA Reshoring: ${usaReshoring[0]}%`, 60, 450)
      ctx.fillText(`• Nearshore Diversification: ${nearshoring[0]}%`, 60, 480)
      
      // Impact Analysis
      ctx.font = 'bold 24px Inter, system-ui, sans-serif'
      ctx.fillStyle = '#10B981'
      ctx.fillText('Impact Analysis', 40, 540)
      
      const mitigatedLoss = calculateMitigatedLoss()
      const reduction = ((1 - mitigatedLoss / currentScenario.economicImpactUSD) * 100).toFixed(0)
      
      ctx.font = '16px Inter, system-ui, sans-serif'
      ctx.fillStyle = '#E2E8F0'
      ctx.fillText(`• Original Economic Loss: ${formatNumber(currentScenario.economicImpactUSD)}`, 60, 580)
      ctx.fillText(`• Mitigated Loss: ${formatNumber(mitigatedLoss)}`, 60, 610)
      ctx.fillStyle = '#10B981'
      ctx.fillText(`• Total Reduction: ${reduction}%`, 60, 640)
      
      // Industry Impacts
      ctx.font = 'bold 24px Inter, system-ui, sans-serif'
      ctx.fillStyle = '#F59E0B'
      ctx.fillText('Industry Impact Breakdown', 40, 700)
      
      ctx.font = '14px Inter, system-ui, sans-serif'
      let yPos = 740
      industryImpacts.forEach((impact) => {
        const adjustedLoss = impact.lossUSD * (currentScenario.productionDropPercent / 95)
        ctx.fillStyle = '#94A3B8'
        ctx.fillText(`${impact.icon} ${impact.industry}:`, 60, yPos)
        ctx.fillStyle = impact.color
        ctx.fillText(`${formatNumber(adjustedLoss)} loss`, 300, yPos)
        yPos += 30
      })
      
      // Scenario Comparison
      ctx.font = 'bold 24px Inter, system-ui, sans-serif'
      ctx.fillStyle = '#8B5CF6'
      ctx.fillText('All Scenarios Comparison', 40, yPos + 40)
      
      yPos += 80
      ctx.font = '14px Inter, system-ui, sans-serif'
      scenarioConfigs.forEach((scenario) => {
        ctx.fillStyle = '#94A3B8'
        ctx.fillText(`${scenario.icon} ${scenario.name}:`, 60, yPos)
        ctx.fillStyle = scenario.id === 'destruction' ? '#DC2626' : 
                        scenario.id === 'blockade' ? '#F97316' :
                        scenario.id === 'quarantine' ? '#F59E0B' : '#10B981'
        ctx.fillText(`${formatNumber(scenario.economicImpactUSD)} | ${scenario.productionDropPercent}% drop | ${scenario.durationMonths}mo`, 350, yPos)
        yPos += 30
      })
      
      // Footer
      ctx.font = '12px Inter, system-ui, sans-serif'
      ctx.fillStyle = '#64748B'
      ctx.fillText('This report is generated for risk assessment purposes. Data sources: CSET, GDELT, MarineTraffic, WSTS.', 40, 1550)
      ctx.fillText('© 2024 Vigia Taiwan Semiconductor Risk Intelligence Platform', 40, 1575)
      
      // Download
      canvas.toBlob((blob) => {
        if (blob) {
          const url = URL.createObjectURL(blob)
          const link = document.createElement('a')
          link.href = url
          link.download = `vigia-risk-report-${currentScenario.id}-${new Date().toISOString().split('T')[0]}.png`
          document.body.appendChild(link)
          link.click()
          document.body.removeChild(link)
          URL.revokeObjectURL(url)
        }
      }, 'image/png')
    }
  }

  return (
    <div className="p-6 lg:p-10">
      {/* Header */}
      <div className="mb-8">
        <h1 className="text-3xl font-heading font-bold text-text-primary mb-2">
          Taiwan Disruption Scenarios: Geopolitical Risk Modeling
        </h1>
        <p className="text-text-muted">
          Quantifying economic impact across quarantine, blockade, and infrastructure destruction scenarios
        </p>
      </div>

      {/* Scenario Tabs */}
      <Tabs value={activeScenario} onValueChange={setActiveScenario} className="mb-8">
        <TabsList className="grid grid-cols-4 w-full max-w-3xl">
          {scenarioConfigs.map((scenario) => (
            <TabsTrigger 
              key={scenario.id} 
              value={scenario.id}
              className={cn(
                'flex items-center gap-2',
                scenario.id === 'destruction' && 'data-[state=active]:bg-taiwan-red/20 data-[state=active]:text-taiwan-red'
              )}
            >
              <span>{scenario.icon}</span>
              <span className="hidden md:inline text-xs">{scenario.name.split(':')[0]}</span>
            </TabsTrigger>
          ))}
        </TabsList>

        {scenarioConfigs.map((scenario) => (
          <TabsContent key={scenario.id} value={scenario.id}>
            {/* Scenario Overview Card */}
            <Card className={cn(
              'mb-8',
              scenario.id === 'destruction' && 'bg-gradient-to-br from-red-900/50 to-red-800/30 border-taiwan-red'
            )}>
              <CardContent className="p-8">
                <div className="flex items-start gap-6">
                  <span className="text-6xl">{scenario.icon === '🔴' ? '💥' : scenario.icon}</span>
                  <div className="flex-1">
                    <h2 className="text-3xl font-bold text-text-primary mb-2">{scenario.name}</h2>
                    <p className="text-text-secondary mb-6">
                      {scenario.id === 'destruction' 
                        ? 'Complete TSMC fab shutdown due to military conflict, earthquake, or intentional sabotage. Recovery requires 3-5 years of global reshoring efforts.'
                        : scenario.id === 'blockade'
                        ? 'Military blockade of Taiwan Strait disrupts shipping and air freight. Partial production continues but exports severely limited.'
                        : scenario.id === 'quarantine'
                        ? 'Economic quarantine and trade restrictions limit Taiwan semiconductor exports. Some alternative shipping routes available.'
                        : 'Current state with 65% Taiwan dependency. No active disruption scenario.'}
                    </p>
                    <div className="grid grid-cols-3 gap-6">
                      <div className="text-center p-4 bg-navy-100/50 rounded-xl">
                        <TrendingDown className="w-6 h-6 mx-auto mb-2 text-taiwan-red" />
                        <p className="text-2xl font-bold text-text-primary">{scenario.productionDropPercent}%</p>
                        <p className="text-xs text-text-muted">Production Drop</p>
                      </div>
                      <div className="text-center p-4 bg-navy-100/50 rounded-xl">
                        <Clock className="w-6 h-6 mx-auto mb-2 text-taiwan-caution" />
                        <p className="text-2xl font-bold text-text-primary">{scenario.durationMonths} mo</p>
                        <p className="text-xs text-text-muted">Duration</p>
                      </div>
                      <div className="text-center p-4 bg-navy-100/50 rounded-xl">
                        <AlertTriangle className="w-6 h-6 mx-auto mb-2 text-taiwan-strategic" />
                        <p className="text-2xl font-bold text-text-primary">{(scenario.probabilityAnnual * 100).toFixed(0)}%</p>
                        <p className="text-xs text-text-muted">Annual Probability</p>
                      </div>
                    </div>
                  </div>
                </div>
              </CardContent>
            </Card>
          </TabsContent>
        ))}
      </Tabs>

      {/* Main Content Grid */}
      <div className="grid grid-cols-1 xl:grid-cols-2 gap-6 mb-8">
        {/* Cascading Industry Impacts */}
        <Card>
          <CardHeader>
            <CardTitle className="text-xl text-taiwan-red flex items-center gap-2">
              <DollarSign className="w-5 h-5" />
              Cascading Industry Impacts
            </CardTitle>
            <p className="text-sm text-text-muted">Economic losses by sector under {currentScenario.name}</p>
          </CardHeader>
          <CardContent>
            <div className="space-y-4">
              {industryImpacts.map((impact, index) => {
                const adjustedLoss = impact.lossUSD * (currentScenario.productionDropPercent / 95)
                const adjustedHalt = Math.min(impact.productionHaltPercent * (currentScenario.productionDropPercent / 95), 100)
                
                return (
                  <div key={index} className="flex items-center gap-4">
                    <span className="text-2xl w-10">{impact.icon}</span>
                    <div className="flex-1">
                      <div className="flex justify-between mb-1">
                        <span className="text-sm font-medium text-text-primary">{impact.industry}</span>
                        <span className="text-sm font-mono" style={{ color: impact.color }}>
                          {formatNumber(adjustedLoss)} loss
                        </span>
                      </div>
                      <div className="h-2 bg-navy-100 rounded-full overflow-hidden">
                        <div 
                          className="h-full rounded-full transition-all duration-500"
                          style={{ 
                            width: `${adjustedHalt}%`,
                            backgroundColor: impact.color
                          }}
                        />
                      </div>
                      <span className="text-xs text-text-muted">{adjustedHalt.toFixed(0)}% production halt</span>
                    </div>
                  </div>
                )
              })}
            </div>

            <div className="mt-6 p-4 bg-navy-100 rounded-xl text-center">
              <p className="text-text-muted text-sm mb-1">Total Economic Impact</p>
              <p className="text-4xl font-bold text-text-emphasis">{formatNumber(currentScenario.economicImpactUSD)}</p>
              <p className="text-xs text-text-muted mt-1">Cumulative GDP loss ({currentScenario.durationMonths}-month scenario)</p>
            </div>
          </CardContent>
        </Card>

        {/* Supply Chain Collapse Timeline */}
        <Card>
          <CardHeader>
            <CardTitle className="text-xl flex items-center gap-2">
              <Clock className="w-5 h-5 text-taiwan-caution" />
              Supply Chain Collapse Timeline
            </CardTitle>
            <p className="text-sm text-text-muted">Progressive impact milestones</p>
          </CardHeader>
          <CardContent>
            <div className="relative">
              {/* Timeline line */}
              <div className="absolute left-4 top-0 bottom-0 w-0.5 bg-gradient-to-b from-taiwan-red via-taiwan-caution to-taiwan-resilience" />
              
              <div className="space-y-6">
                {timelineEvents.map((event, index) => (
                  <div key={index} className="relative pl-12">
                    {/* Timeline dot */}
                    <div className={cn(
                      'absolute left-2 w-5 h-5 rounded-full border-2 border-navy',
                      event.severity === 'CRITICAL' ? 'bg-taiwan-red' :
                      event.severity === 'HIGH' ? 'bg-risk-high' :
                      event.severity === 'MEDIUM' ? 'bg-taiwan-caution' :
                      'bg-taiwan-resilience'
                    )} />
                    
                    <div className={cn(
                      'p-4 rounded-xl border-l-4',
                      event.severity === 'CRITICAL' ? 'bg-taiwan-red/10 border-taiwan-red' :
                      event.severity === 'HIGH' ? 'bg-risk-high/10 border-risk-high' :
                      event.severity === 'MEDIUM' ? 'bg-taiwan-caution/10 border-taiwan-caution' :
                      'bg-taiwan-resilience/10 border-taiwan-resilience'
                    )}>
                      <div className="flex items-center justify-between mb-1">
                        <span className="text-xs font-mono text-text-muted">{event.period}</span>
                        <span className={cn(
                          'text-[10px] px-2 py-0.5 rounded-full font-semibold',
                          event.severity === 'CRITICAL' ? 'bg-taiwan-red/20 text-taiwan-red' :
                          event.severity === 'HIGH' ? 'bg-risk-high/20 text-risk-high' :
                          event.severity === 'MEDIUM' ? 'bg-taiwan-caution/20 text-taiwan-caution' :
                          'bg-taiwan-resilience/20 text-taiwan-resilience'
                        )}>
                          {event.severity}
                        </span>
                      </div>
                      <h4 className="text-sm font-semibold text-text-primary mb-1">{event.title}</h4>
                      <p className="text-xs text-text-secondary">{event.description}</p>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Mitigation Strategy Simulator */}
      <Card className="border-l-4 border-taiwan-strategic">
        <CardHeader>
          <CardTitle className="text-2xl text-taiwan-strategic">
            Test Resilience Strategies Against This Scenario
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="grid grid-cols-1 lg:grid-cols-4 gap-8">
            {/* Strategy Sliders */}
            <div className="lg:col-span-3 grid grid-cols-1 md:grid-cols-3 gap-6">
              <div className="p-4 bg-navy-100 rounded-xl">
                <div className="flex justify-between mb-2">
                  <label className="text-sm font-medium text-text-primary">Strategic Stockpile</label>
                  <span className="text-sm font-mono text-taiwan-resilience">{stockpileDays} days</span>
                </div>
                <Slider
                  value={stockpileDays}
                  onValueChange={setStockpileDays}
                  max={180}
                  step={5}
                  className="mb-3"
                />
                <p className="text-xs text-taiwan-resilience">
                  Extends survival window by {stockpileDays} days
                </p>
                <p className="text-xs text-text-muted mt-1">
                  Cost: ${((stockpileDays[0] / 45) * 12).toFixed(0)}B investment
                </p>
              </div>

              <div className="p-4 bg-navy-100 rounded-xl">
                <div className="flex justify-between mb-2">
                  <label className="text-sm font-medium text-text-primary">USA Reshoring</label>
                  <span className="text-sm font-mono text-taiwan-strategic">{usaReshoring}%</span>
                </div>
                <Slider
                  value={usaReshoring}
                  onValueChange={setUsaReshoring}
                  max={100}
                  step={5}
                  className="mb-3"
                />
                <p className="text-xs text-taiwan-resilience">
                  Reduces recovery time to {Math.max(12, 24 - (usaReshoring[0] / 100) * 12).toFixed(0)} months
                </p>
                <p className="text-xs text-text-muted mt-1">
                  Cost: ${((usaReshoring[0] / 50) * 85).toFixed(0)}B CHIPS Act funding
                </p>
              </div>

              <div className="p-4 bg-navy-100 rounded-xl">
                <div className="flex justify-between mb-2">
                  <label className="text-sm font-medium text-text-primary">Nearshore Diversification</label>
                  <span className="text-sm font-mono text-taiwan-ai">{nearshoring}%</span>
                </div>
                <Slider
                  value={nearshoring}
                  onValueChange={setNearshoring}
                  max={50}
                  step={5}
                  className="mb-3"
                />
                <p className="text-xs text-taiwan-resilience">
                  Preserves {15 + nearshoring[0]}% manufacturing capacity
                </p>
                <p className="text-xs text-text-muted mt-1">
                  Cost: {15 + (nearshoring[0] / 50) * 10}% higher unit costs
                </p>
              </div>
            </div>

            {/* Results Preview */}
            <div className="p-6 bg-navy-100 rounded-xl">
              <h4 className="text-sm font-semibold text-text-primary mb-4">Mitigated Impact</h4>
              
              <div className="space-y-4">
                <div>
                  <p className="text-xs text-text-muted">Original Loss</p>
                  <p className="text-xl font-bold text-taiwan-red line-through">
                    {formatNumber(currentScenario.economicImpactUSD)}
                  </p>
                </div>
                
                <div>
                  <p className="text-xs text-text-muted">Mitigated Loss</p>
                  <p className="text-2xl font-bold text-taiwan-resilience">
                    {formatNumber(calculateMitigatedLoss())}
                  </p>
                </div>

                <div className="pt-2 border-t border-navy-200">
                  <p className="text-xs text-text-muted">Reduction</p>
                  <p className="text-lg font-bold text-taiwan-resilience">
                    -{((1 - calculateMitigatedLoss() / currentScenario.economicImpactUSD) * 100).toFixed(0)}%
                  </p>
                </div>
              </div>

              <Button 
                className="w-full mt-4" 
                size="sm"
                onClick={handleRecalculate}
                disabled={isRecalculating}
              >
                <RefreshCw className={cn("w-4 h-4 mr-2", isRecalculating && "animate-spin")} />
                {isRecalculating ? 'Calculating...' : 'Recalculate'}
              </Button>
            </div>
          </div>

          {/* Action Buttons */}
          <div className="flex gap-4 mt-6">
            <Button onClick={() => setShowCompareModal(true)}>
              <BarChart3 className="w-4 h-4 mr-2" />
              Compare All Scenarios
            </Button>
            <Button variant="outline" onClick={handleExportReport}>
              <Download className="w-4 h-4 mr-2" />
              Export Risk Report
            </Button>
          </div>
        </CardContent>
      </Card>

      {/* Compare Scenarios Modal */}
      {showCompareModal && (
        <div className="fixed inset-0 bg-black/70 flex items-center justify-center z-50 p-4">
          <div className="bg-navy w-full max-w-5xl max-h-[90vh] overflow-auto rounded-2xl border border-navy-200 shadow-2xl">
            {/* Modal Header */}
            <div className="flex items-center justify-between p-6 border-b border-navy-200 sticky top-0 bg-navy z-10">
              <div>
                <h2 className="text-2xl font-bold text-text-primary">Scenario Comparison Matrix</h2>
                <p className="text-sm text-text-muted">Compare all disruption scenarios with current mitigation settings</p>
              </div>
              <Button 
                variant="ghost" 
                size="sm" 
                onClick={() => setShowCompareModal(false)}
                className="h-10 w-10 p-0"
              >
                <X className="w-5 h-5" />
              </Button>
            </div>

            {/* Modal Content */}
            <div className="p-6">
              {/* Comparison Table */}
              <div className="overflow-x-auto">
                <table className="w-full">
                  <thead>
                    <tr className="border-b border-navy-200">
                      <th className="text-left py-3 px-4 text-sm font-semibold text-text-primary">Scenario</th>
                      <th className="text-center py-3 px-4 text-sm font-semibold text-text-primary">Production Drop</th>
                      <th className="text-center py-3 px-4 text-sm font-semibold text-text-primary">Duration</th>
                      <th className="text-center py-3 px-4 text-sm font-semibold text-text-primary">Probability</th>
                      <th className="text-right py-3 px-4 text-sm font-semibold text-text-primary">Original Impact</th>
                      <th className="text-right py-3 px-4 text-sm font-semibold text-text-primary">Mitigated Impact</th>
                      <th className="text-right py-3 px-4 text-sm font-semibold text-text-primary">Savings</th>
                    </tr>
                  </thead>
                  <tbody>
                    {scenarioConfigs.map((scenario) => {
                      const mitigated = calculateMitigatedLoss(scenario)
                      const savings = scenario.economicImpactUSD - mitigated
                      const savingsPercent = ((savings / scenario.economicImpactUSD) * 100).toFixed(0)
                      
                      return (
                        <tr 
                          key={scenario.id} 
                          className={cn(
                            "border-b border-navy-200 hover:bg-navy-100 transition-colors",
                            scenario.id === activeScenario && "bg-taiwan-strategic/10"
                          )}
                        >
                          <td className="py-4 px-4">
                            <div className="flex items-center gap-3">
                              <span className="text-2xl">{scenario.icon}</span>
                              <div>
                                <p className="font-medium text-text-primary">{scenario.name.split(':')[0]}</p>
                                <p className="text-xs text-text-muted">{scenario.name.split(':')[1]}</p>
                              </div>
                              {scenario.id === activeScenario && (
                                <span className="text-[10px] px-2 py-0.5 bg-taiwan-strategic/20 text-taiwan-strategic rounded-full">
                                  Active
                                </span>
                              )}
                            </div>
                          </td>
                          <td className="text-center py-4 px-4">
                            <span className={cn(
                              "font-mono font-bold",
                              scenario.productionDropPercent >= 80 ? "text-taiwan-red" :
                              scenario.productionDropPercent >= 50 ? "text-risk-high" :
                              scenario.productionDropPercent >= 20 ? "text-taiwan-caution" :
                              "text-taiwan-resilience"
                            )}>
                              {scenario.productionDropPercent}%
                            </span>
                          </td>
                          <td className="text-center py-4 px-4">
                            <span className="font-mono text-text-secondary">{scenario.durationMonths} mo</span>
                          </td>
                          <td className="text-center py-4 px-4">
                            <span className="font-mono text-text-secondary">
                              {(scenario.probabilityAnnual * 100).toFixed(0)}%
                            </span>
                          </td>
                          <td className="text-right py-4 px-4">
                            <span className="font-mono text-taiwan-red">
                              {formatNumber(scenario.economicImpactUSD)}
                            </span>
                          </td>
                          <td className="text-right py-4 px-4">
                            <span className="font-mono text-taiwan-caution">
                              {formatNumber(mitigated)}
                            </span>
                          </td>
                          <td className="text-right py-4 px-4">
                            <div>
                              <span className="font-mono text-taiwan-resilience font-bold">
                                {formatNumber(savings)}
                              </span>
                              <span className="text-xs text-taiwan-resilience ml-1">
                                (-{savingsPercent}%)
                              </span>
                            </div>
                          </td>
                        </tr>
                      )
                    })}
                  </tbody>
                </table>
              </div>

              {/* Current Mitigation Settings */}
              <div className="mt-6 p-4 bg-navy-100 rounded-xl">
                <h4 className="text-sm font-semibold text-text-primary mb-3">Current Mitigation Settings Applied</h4>
                <div className="grid grid-cols-3 gap-4">
                  <div className="text-center">
                    <p className="text-2xl font-bold text-taiwan-resilience">{stockpileDays[0]} days</p>
                    <p className="text-xs text-text-muted">Strategic Stockpile</p>
                  </div>
                  <div className="text-center">
                    <p className="text-2xl font-bold text-taiwan-strategic">{usaReshoring[0]}%</p>
                    <p className="text-xs text-text-muted">USA Reshoring</p>
                  </div>
                  <div className="text-center">
                    <p className="text-2xl font-bold text-taiwan-ai">{nearshoring[0]}%</p>
                    <p className="text-xs text-text-muted">Nearshore Diversification</p>
                  </div>
                </div>
              </div>

              {/* Summary Stats */}
              <div className="mt-6 grid grid-cols-2 gap-4">
                <div className="p-4 bg-taiwan-red/10 border border-taiwan-red/30 rounded-xl">
                  <p className="text-sm text-text-muted mb-1">Total Potential Loss (All Scenarios)</p>
                  <p className="text-3xl font-bold text-taiwan-red">
                    {formatNumber(scenarioConfigs.reduce((sum, s) => sum + s.economicImpactUSD, 0))}
                  </p>
                </div>
                <div className="p-4 bg-taiwan-resilience/10 border border-taiwan-resilience/30 rounded-xl">
                  <p className="text-sm text-text-muted mb-1">Total Mitigated Savings</p>
                  <p className="text-3xl font-bold text-taiwan-resilience">
                    {formatNumber(scenarioConfigs.reduce((sum, s) => sum + (s.economicImpactUSD - calculateMitigatedLoss(s)), 0))}
                  </p>
                </div>
              </div>
            </div>

            {/* Modal Footer */}
            <div className="flex justify-end gap-3 p-6 border-t border-navy-200 sticky bottom-0 bg-navy">
              <Button variant="outline" onClick={() => setShowCompareModal(false)}>
                Close
              </Button>
              <Button onClick={() => { handleExportReport(); setShowCompareModal(false); }}>
                <Download className="w-4 h-4 mr-2" />
                Export Comparison Report
              </Button>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}
